[tool.poetry]
name = "check_ipv6_address"
version = "0.1.0"
description = "A nagios check for finding the local subnet."
authors = ["James Hodgkinson <james@terminaloutcomes.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"

[tool.poetry.dev-dependencies]
mypy = "^0.991"
pylint = "^2.16.1"
pytest = "^7.2.1"
black = "^23.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
'check_ipv6_address' = 'check_ipv6_address.py:cli()'
